In [50]:
import numpy as np
import pandas as pd

In [59]:
def relu(X):
    return np.maximum(0, X)

def softmax(X):
    return np.exp(X) / sum(np.exp(X))

class Layer:
    def __init__(self, n_input, n_output):
        self.W = np.random.randn(n_input, n_output)
        self.b = np.random.randn(n_output, 1)

    def forward(self, X):
        # if X.ndim == 1:
        #     X = X.reshape(-1, 1)
        print(self.b)
        return relu(self.W.dot(X) + self.b)

# NOTE: last layer should be softmax, last layer should not be mentioned at the time of network creation

class Network:
    def __init__(self, layer_size = [2, 2], epochs=10):
        self.layers = []
        self.layer_size = layer_size
        self.epochs = epochs
        
    def compile(self):
        """
        Layers would be created and Weights would be initialized in this method
        """
        for n_input, n_output in zip(self.layer_size[:-1], self.layer_size[1:]):
            self.layers.append(Layer(n_input, n_output))
        
    def train(self, X, y):
        # mse
        for epoch in range(self.epochs):
            outputs = []
            temp_outputs = []
            errors = []
            temp_outputs.append(X)
            for layer in self.layers:
                temp_outputs.append(layer.forward(temp_outputs[-1]))
            outputs.append(softmax(temp_outputs[-1]))
            print(outputs)
            errors.append((y - outputs[-1]))
            print(">> Errors : ", errors)

In [60]:
X = np.array([[0, 1, 0, 1], 
    [0, 0, 1, 1]])
y = np.array([0, 1, 1, 0])
nn = Network()
nn.compile()
nn.train(X, y)

[[0.58250731]
 [0.32001608]]
[array([[0.56524859, 0.65184728, 0.61794631, 0.62843345],
       [0.43475141, 0.34815272, 0.38205369, 0.37156655]])]
>> Errors :  [array([[-0.56524859,  0.34815272,  0.38205369, -0.62843345],
       [-0.43475141,  0.65184728,  0.61794631, -0.37156655]])]
[[0.58250731]
 [0.32001608]]
[array([[0.56524859, 0.65184728, 0.61794631, 0.62843345],
       [0.43475141, 0.34815272, 0.38205369, 0.37156655]])]
>> Errors :  [array([[-0.56524859,  0.34815272,  0.38205369, -0.62843345],
       [-0.43475141,  0.65184728,  0.61794631, -0.37156655]])]
[[0.58250731]
 [0.32001608]]
[array([[0.56524859, 0.65184728, 0.61794631, 0.62843345],
       [0.43475141, 0.34815272, 0.38205369, 0.37156655]])]
>> Errors :  [array([[-0.56524859,  0.34815272,  0.38205369, -0.62843345],
       [-0.43475141,  0.65184728,  0.61794631, -0.37156655]])]
[[0.58250731]
 [0.32001608]]
[array([[0.56524859, 0.65184728, 0.61794631, 0.62843345],
       [0.43475141, 0.34815272, 0.38205369, 0.37156655]])]
>>