In [1]:
a_s = [1,2,3]
b_s = [1,2,3]
c_s = [1,2,3]

In [2]:
for a, b, c in (a_s, b_s, c_s):
    print(a, b, c)

1 2 3
1 2 3
1 2 3


In [3]:
for a, b, c in zip(a_s, b_s, c_s):
    print(a, b, c)

1 1 1
2 2 2
3 3 3


In [4]:
a_s[:-1]

[1, 2]

In [5]:
a_s[-1]

3

In [6]:
a_s[:1]

[1]

In [7]:
a_s[1:]

[2, 3]

In [8]:
l1 = [[1,2,3], [4,5,6], [7,8,9]]
[max(inner_list) for inner_list in l1]

[3, 6, 9]

In [9]:
a = set((2,3,1))
type(a), a

(set, {1, 2, 3})

In [10]:
from tqdm import trange
import time

def process_item(item):
    # Simulating some time-consuming process
    time.sleep(0.01)
    return item * 2

# Using the loop structure you asked about
results = []
for i in (t := trange(100)):
    result = process_item(i)
    results.append(result)
    
    # You can use 't' to update the progress bar description
    if i % 10 == 0:
        t.set_description(f"Processing item {i}")

print("Processing complete!")
print(f"First few results: {results[:5]}")


Processing item 90: 100%|███████████████████████████████████████████████| 100/100 [00:01<00:00, 94.69it/s]

Processing complete!
First few results: [0, 2, 4, 6, 8]


In [11]:
def square(num):
    return num ** 2

numbers = [1, 2, 3, 4]
squared_numbers = map(square, numbers)
print(list(squared_numbers))

[1, 4, 9, 16]


In [12]:
numbers = [1, 2, 3, 4]
squared_numbers = map(lambda x: x ** 2, numbers)

print(list(squared_numbers))


[1, 4, 9, 16]


In [13]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
a[:][0::2]

[[1, 2, 3], [7, 8, 9]]

In [14]:
a[0::2][:]

[[1, 2, 3], [7, 8, 9]]

In [15]:
import torch
a = torch.Tensor(a)

In [16]:
a[:, 0::2]

tensor([[ 1.,  3.],
        [ 4.,  6.],
        [ 7.,  9.],
        [10., 12.]])

In [17]:
a[0::2, :]

tensor([[1., 2., 3.],
        [7., 8., 9.]])

In [18]:
b = a.unsqueeze(1)
b, a

(tensor([[[ 1.,  2.,  3.]],
 
         [[ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.]],
 
         [[10., 11., 12.]]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [19]:
b.squeeze(1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [20]:
10**-1, 1e-1

(0.1, 0.1)

In [21]:
torch.arange(0,10,2).float().unsqueeze(1)

tensor([[0.],
        [2.],
        [4.],
        [6.],
        [8.]])

In [22]:
torch.exp(torch.tensor(1))

tensor(2.7183)

In [23]:
a.mean(-1), a

(tensor([ 2.,  5.,  8., 11.]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [24]:
3/4, 3//4

(0.75, 0)

In [38]:
b = [[[i for i in range(3)] for i in range(3,6)] for i in range(6,9) for i in range(6,9)]
b

[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]

In [43]:
b = torch.tensor(b)
b.view(b.shape[0], b.shape[1], 3, 1).shape

/tmp/ipykernel_3624/3723956176.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(b)


torch.Size([9, 3, 3, 1])

In [40]:
b.shape

torch.Size([9, 3, 3])

In [44]:
a, a.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [51]:
a.view(2,2,3).transpose(1, 2), a.view(2,2,3)

(tensor([[[ 1.,  4.],
          [ 2.,  5.],
          [ 3.,  6.]],
 
         [[ 7., 10.],
          [ 8., 11.],
          [ 9., 12.]]]),
 tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]]]))