* Common activation functions used for Perceptrons are (with threshold at 0)-

$$step(z)\ or\ heaviside(z) = \left\{\begin{matrix}
0 & z<0\\
1 & z\geq 0
\end{matrix}\right.$$

* Perceptron learning Rule:
$$w_{i,j} \leftarrow w_{i,j} + \eta(y_j - \hat{y_j})x_i$$
where,
  * $w_{i,j}$ : connection weight between $i^{th}$ input neuron and $j^{th}$ output neuron
  * $x_i$ : $i^{th}$ input value.
  * $\hat{y_j}$ : output of $j^{th}$ output neuron
  * $y_j$ : target output of $j^{th}$ output neuron
  * $\eta$ : learning rate
 
$\mathbf{z'} = w_0 x_0 + w_1 x_1 + w_2 x_2 + ... + w_n x_n$

and

$\phi(z) = \begin{cases}
+1 & \text{ if } z \geq 0\\
-1 & \text{ if } z < 0
\end{cases}$

here $w_0 x_0$ is usually known as bias unit

In [15]:
import numpy as np
import pandas as pd

/home/darshan/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [51]:

class Perceptron:
    def __init__(self, epochs, eta):
        self.epochs = epochs
        self.eta = eta
        self.weights = np.random.randn(3) * 1e-4
        print(f"Weights : {self.weights}")
        
    def activation_function(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z>0, 1, 0)

    def fit(self, X, y):
        self.X = X
        self.y = y
        X_with_bias = np.c_[X, -np.ones( (len(X),1) )]
        print(f"X with bias : {X_with_bias}")
        for epoch in range(self.epochs):
            print(f"\nEpoch : {epoch}")
            y_hat = self.activation_function(X_with_bias, self.weights)
            print(f"Y hat : {y_hat}")
            error = self.y - y_hat
            print(f"Error : {error}")
            self.weights = self.weights + (self.eta * np.dot(X_with_bias.T, error))

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones( (len(X), 1) )]
        return self.activation_function(X_with_bias, self.weights)

In [52]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
X = AND.drop("y", axis=1)
y = AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [53]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

Weights : [-2.93026232e-05  1.64487380e-04 -7.27060492e-05]
X with bias : [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]

Epoch : 0
Y hat : [1 1 1 1]
Error : 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64

Epoch : 1
Y hat : [0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64

Epoch : 2
Y hat : [0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64

Epoch : 3
Y hat : [0 1 1 1]
Error : 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64

Epoch : 4
Y hat : [0 0 0 0]
Error : 0    0
1    0
2    0
3    1
Name: y, dtype: int64

Epoch : 5
Y hat : [0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64

Epoch : 6
Y hat : [0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64

Epoch : 7
Y hat : [0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64

Epoch : 8
Y hat : [0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: int64

Epoch : 9
Y hat : [0 0 0 1]
Error : 0    0
1    0
2    0
3    0
Name: y, dtype: i

In [54]:
model.predict(X)

array([0, 0, 0, 1])

In [56]:
model.weights

array([0.4999707 , 0.50016449, 0.99992729])